/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// int __fastcall _cxa_finalize(_DWORD); weak
// void *memcpy(void *, const void *, size_t);
// void free(void *);
// int strcmp(const char *, const char *);
// int _android_log_print(_DWORD, _DWORD, const char *, ...); weak
// int __fastcall open(_DWORD, _DWORD); weak
// int __cdecl close(_DWORD, _DWORD); weak
// void *malloc(size_t);
// void *memset(void *, int, size_t);
// int _sprintf_chk(_DWORD, _DWORD, _DWORD, const char *, ...); weak
// int __fastcall _strlen_chk(_DWORD, _DWORD); weak
// int __fastcall strlcat(_DWORD, _DWORD, _DWORD); weak
// char *strcpy(char *, const char *);
// int __fastcall clock_gettime(_DWORD, _DWORD); weak
// int __cdecl _errno(_DWORD); weak
// int __fastcall sched_yield(_DWORD); weak
// int __fastcall write(_DWORD, _DWORD, _DWORD); weak
// int __fastcall _stack_chk_fail(_DWORD); weak
// int __fastcall pthread_mutex_lock(_DWORD); weak
// int __fastcall pthread_mutex_unlock(_DWORD); weak
int sub_7C0();
int (*__fastcall sub_7E0(int (*result)(void)))(void);
int sub_854(); // weak
signed int __fastcall sub_858(int a1, unsigned int a2, void *a3);
int __fastcall sub_878(void *a1);
signed int __fastcall sub_884(int a1, const char *a2, _DWORD *a3);
int __fastcall sub_9B8(int a1, int a2, int a3);
int __fastcall sub_BC0(int a1, int a2, int a3, int a4);

//-------------------------------------------------------------------------
// Data declarations

int dword_B88[2] = { 1000000000, 0 }; // weak
_UNKNOWN unk_D7F; // weak
void *off_2000 = &off_2000; // weak
int dword_2004 = 4294967295; // weak
_UNKNOWN unk_208C; // weak
// extern _UNKNOWN _stack_chk_guard; weak


//----- (000007C0) --------------------------------------------------------
int sub_7C0()
{
  return _cxa_finalize(&off_2000);
}
// 6B8: using guessed type int __fastcall _cxa_finalize(_DWORD);
// 2000: using guessed type void *off_2000;

//----- (000007E0) --------------------------------------------------------
int (*__fastcall sub_7E0(int (*result)(void)))(void)
{
  if ( result )
    result = (int (*)(void))result();
  return result;
}

//----- (00000858) --------------------------------------------------------
signed int __fastcall sub_858(int a1, unsigned int a2, void *a3)
{
  signed int v3; // r4@2

  if ( a2 >= 1 )
    v3 = 1;
  else
    v3 = a2;
  memcpy(a3, "Ç>", 8 * v3);
  return v3;
}

//----- (00000878) --------------------------------------------------------
int __fastcall sub_878(void *a1)
{
  free(a1);
  return 0;
}

//----- (00000884) --------------------------------------------------------
signed int __fastcall sub_884(int a1, const char *a2, _DWORD *a3)
{
  int v3; // r8@1
  _DWORD *v4; // r6@1
  int v5; // r4@1
  int v6; // r0@5
  int v7; // r1@5
  const char *v8; // r1@6
  const char *v9; // r2@6
  void *v10; // r7@12
  const char *v12; // [sp+4h] [bp-1Ch]@1

  v12 = a2;
  v3 = a1;
  v4 = a3;
  v5 = strcmp(a2, "transmitter");
  if ( v5 )
    return -22;
  if ( !v4 )
  {
    _android_log_print(6, "ConsumerIrHal", "NULL device on open");
    return -22;
  }
  if ( dword_2004 < 0 )
  {
    _android_log_print(3, "ConsumerIrHal", "Try to use F Chip.");
    v6 = open("/sys/class/sec/sec_ir/ir_send", 1);
    if ( v6 < 0 )
    {
      v8 = "ConsumerIrHal";
      v9 = "Consumer IR HAL is failed to load (F Chip)";
      goto LABEL_11;
    }
    dword_2004 = 0;
    if ( close(v6, v7) < 0 )
      _android_log_print(6, "ConsumerIrHal", "Fail to close fd : F");
  }
  if ( dword_2004 >= 0 )
  {
    _android_log_print(
      3,
      "ConsumerIrHal",
      "Consumer IR HAL is going to be loaded [Type : %s] [SOL : %d]",
      "TIME",
      dword_2004,
      v12);
    v10 = malloc(0x60u);
    memset(v10, 0, 0x60u);
    *(_DWORD *)v10 = 1213678676;
    *((_DWORD *)v10 + 2) = v3;
    *((_DWORD *)v10 + 15) = sub_878;
    *((_DWORD *)v10 + 16) = sub_BC0;
    *((_DWORD *)v10 + 17) = sub_854;
    *((_DWORD *)v10 + 18) = sub_858;
    *v4 = v10;
    return v5;
  }
  v8 = "ConsumerIrHal";
  v9 = "Consumer IR Hal is failed to load !";
LABEL_11:
  _android_log_print(6, v8, v9);
  return -2;
}
// 6F4: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 700: using guessed type int __fastcall open(_DWORD, _DWORD);
// 70C: using guessed type int __cdecl close(_DWORD, _DWORD);
// 854: using guessed type int sub_854();
// 2004: using guessed type int dword_2004;

//----- (000009B8) --------------------------------------------------------
int __fastcall sub_9B8(int a1, int a2, int a3)
{
  int v3; // r5@1
  int v4; // r10@1
  int v5; // r4@1
  int i; // r4@1
  const char *v7; // r3@4
  int result; // r0@7
  signed int v9; // r11@9
  int v10; // r0@10
  int v11; // r5@10
  _DWORD *v12; // r0@10
  _DWORD *v13; // r4@10
  _DWORD *v14; // r3@10
  bool v15; // r2@15
  int v16; // r0@21
  int v17; // r1@21
  int v18; // r0@23
  int v19; // [sp+0h] [bp-1060h]@1
  _DWORD *v20; // [sp+8h] [bp-1058h]@13
  int v21; // [sp+14h] [bp-104Ch]@9
  int v22; // [sp+18h] [bp-1048h]@9
  int v23; // [sp+1Ch] [bp-1044h]@13
  int v24; // [sp+20h] [bp-1040h]@16
  int v25; // [sp+24h] [bp-103Ch]@6
  char v26; // [sp+74h] [bp-FECh]@9
  int v27; // [sp+1074h] [bp+14h]@1
  int v28; // [sp+2074h] [bp+1014h]@1

  v3 = a3;
  v4 = a2;
  v5 = a1;
  v28 = _stack_chk_guard;
  memset(&v27, 0, 0x1000u);
  v19 = v5;
  _sprintf_chk(&v27, 0, 4096, "%d,");
  _strlen_chk(&v27, 4096);
  for ( i = 0; i < v3; ++i )
  {
    if ( i == v3 - 1 )
      v7 = (const char *)&unk_D7F;
    else
      v7 = ",";
    _sprintf_chk(&v25, 0, 80, "%d%s", *(_DWORD *)(v4 + 4 * i), v7);
    if ( strlcat(&v27, &v25, 4096) >= 4096 )
    {
      _android_log_print(6, "ConsumerIrHal", "Error: too many pattern\n");
      result = -7;
      goto LABEL_26;
    }
  }
  strcpy(&v26, "/sys/class/sec/sec_ir/ir_send");
  clock_gettime(1, &v21);
  v9 = 10;
  v21 += (unsigned __int64)(v22 + 100000000) / *(_QWORD *)dword_B88;
  v22 = (unsigned __int64)(v22 + 100000000) % *(_QWORD *)dword_B88;
  do
  {
    v10 = open(&v26, 1);
    v11 = v10;
    v12 = (_DWORD *)_errno(v10);
    v13 = v12;
    v14 = (_DWORD *)*v12;
    if ( v11 >= 0 )
      break;
    if ( *v12 != 4 )
    {
      v12 = (_DWORD *)*v12;
      if ( v12 != (_DWORD *)13 )
      {
        v20 = v14;
        clock_gettime(1, &v23);
        v12 = v20;
        v15 = v23 > v21 || v23 == v21 && v24 > v22;
        if ( v15 )
        {
          _android_log_print(6, "ConsumerIrHal", "Failed to open! (err=%d)", -(signed int)v20, v19);
          result = -(signed int)v20;
          goto LABEL_26;
        }
      }
    }
    sched_yield(v12);
    --v9;
  }
  while ( v9 );
  v16 = _strlen_chk(&v27, 4096);
  if ( write(v11, &v27, v16) >= 0 )
  {
    v18 = close(v11, v17);
    if ( !((v18 + 1 < 0) ^ __OFADD__(v18, 1)) )
    {
      result = 0;
      goto LABEL_26;
    }
  }
  else
  {
    close(v11, v17);
  }
  result = -*v13;
LABEL_26:
  if ( v28 != _stack_chk_guard )
    _stack_chk_fail(result);
  return result;
}
// 6F4: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 700: using guessed type int __fastcall open(_DWORD, _DWORD);
// 70C: using guessed type int __cdecl close(_DWORD, _DWORD);
// 730: using guessed type int _sprintf_chk(_DWORD, _DWORD, _DWORD, const char *, ...);
// 73C: using guessed type int __fastcall _strlen_chk(_DWORD, _DWORD);
// 748: using guessed type int __fastcall strlcat(_DWORD, _DWORD, _DWORD);
// 760: using guessed type int __fastcall clock_gettime(_DWORD, _DWORD);
// 778: using guessed type int __cdecl _errno(_DWORD);
// 784: using guessed type int __fastcall sched_yield(_DWORD);
// 790: using guessed type int __fastcall write(_DWORD, _DWORD, _DWORD);
// 79C: using guessed type int __fastcall _stack_chk_fail(_DWORD);
// B88: using guessed type int dword_B88[2];

//----- (00000BC0) --------------------------------------------------------
int __fastcall sub_BC0(int a1, int a2, int a3, int a4)
{
  int v4; // r4@1
  int v5; // r6@1
  int v6; // r7@1
  int v7; // r7@1

  v4 = a4;
  v5 = a3;
  v6 = a2;
  _android_log_print(3, "ConsumerIrHal", "Consumer IR HAL is going to transmit - Type : %d", dword_2004, a4);
  pthread_mutex_lock(&unk_208C);
  v7 = sub_9B8(v6, v5, v4);
  if ( v7 < 0 )
    _android_log_print(6, "ConsumerIrHal", "Consumer IR Transmit Failed. - CIR (err = %d)", v7);
  pthread_mutex_unlock(&unk_208C);
  return v7;
}
// 6F4: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 7A8: using guessed type int __fastcall pthread_mutex_lock(_DWORD);
// 7B4: using guessed type int __fastcall pthread_mutex_unlock(_DWORD);
// 2004: using guessed type int dword_2004;

// ALL OK, 7 function(s) have been successfully decompiled